dataset:
  name: "CIFAR10LT"
  parameters:
    root: "datasets/cifar10/"
    imb_factor: 50
    download: True
dataloader:
  name: "StandardDataloader"
  parameters:
    batch_size: 128
optimizer:
  name: "SGD"
  parameters:
    lr: 0.1
    momentum: 0.9
    weight_decay: 2e-4
model:
  name: "ResNet32"
  parameters: None
loss:
  name: "InputMixupLoss"
  parameters:
    alpha: 1.0
transform:
  train_transforms:  # Transforms that are used for training.
    - name: "ToTensor"
      parameters: "None"

    - name: "Normalize"
      parameters:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]

    - name: "ColorJitter"
      parameters:
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.25

    - name: "Pad"
      parameters:
        padding: 4
        fill: 0
        padding_mode: "constant"

    - name: "RandomResizedCrop"
      parameters:
        size: 32

  test_transforms:  # Transforms that are used for testing.
    - name: "CenterCrop"
      parameters:
        size: 32

# Eval & Benchmark can be different from the other bases,
# TODO Their structures are to be decided...
evaluation:
  name:
  parameters:
benchmark: # Rename this component: visualization? data presentation?
  name:
  parameters:
    # TODO List wandb, tensorflow etc...
    # TODO plotting options should be used here
""