Dataset:
  name: "IMB_CIFAR10"
  cifar10_imb_factor: 100
DataGeneration:
  batch_size: 128
  datasets_path: "datasets/"
  train_shuffle: True
  draw_plots: False
  # Note that sampler is not passed through config file
Training:
  epoch_count: 1
  multi_gpu: False
  backup:
    save_models: False
    #models_path: ""
    #load_models: False
  tasks:
    -
      model: "resnet32"
      loss: "focal"
      #evaluation: ...
      task_options:
        init_fc_bias: True
    -
      model: "resnet32"
      loss: "cb_focal"
      #evaluation: ...
  printing:
    print_training: True
    print_frequency: 10
  draw_plots: False
