Dataset:
  name: "IMB_CIFAR10"
  cifar10_imb_factor: 100
DataGeneration:
  batch_size: 128
  datasets_path: "datasets/"
  train_shuffle: True
  draw_plots: False
  # Note that sampler is not passed through config file
Training:
  epoch_count: 1
  multi_gpu: False
  backup:
    save_models: False
    #models_path: ""
    #load_models: False
  tasks:
    -
      model: "resnet32"
      loss: "focal"
      #evaluation: ...
      task_options:
        init_fc_bias: True
        focal_loss_gamma: 0.5
    -
      model: "resnet32"
      loss: "cb_focal"
      #evaluation: ...
      task_options:
        init_fc_bias: True
        focal_loss_gamma: 0.5
  optimizer:
    name: "sgd_linwarmup"
    params:
      lr: 0.1
      lr_decay_epochs: [160, 180]
      lr_decay_rate: 0.1
      momentum: 0.9
      weight_decay: 2e-4
      warmup_epochs: 5
  printing:
    print_training: True
    print_epoch_frequency: 1
    print_batch_frequency: 200
  plotting:
    draw_loss_plots: False
    plot_size: (16, 12)
