Dataset:
  dataset_name: 'CIFAR10LT'
  dataset_parameters:
    root: "datasets/cifar10/"
    imb_factor: 50
    download: True
Dataloader:
  # dataloader_name: '...'
  dataloader_parameters:
    param1: '...'
    paramN: '...'
Optim:
  optimizer_name: 'SGD'
  optimizer_parameters:
    param1: '...'
    paramN: '...'
Model:
  model_name: 'ResNet32'
  model_parameters:
    param1: '...'
    paramN: '...'
Loss:
  loss_name: 'FocalLoss'
  loss_parameters:
    custom_implementation: True  # TODO: Test also with false
    gamma: 0.5
Transform:
  train_transform: #Transforms that is used for training.
    -
      transform_name: 'name1'
      transform_params:
        param11: '...'
        param1N: '...',
    -
      transform_name: 'nameN'
      transform_params:
        paramN1: '...'
        paramNN: '...'
  test_transform: #Transforms that is used for testing.
    -
      transform_name: 'name1'
      transform_params:
        param11: '...'
        param1N: '...',
    -
      transform_name: 'nameN'
      transform_params:
        paramN1: '...'
        paramNN: '...'

#Eval & Benchmark can be different from the other bases,
#Their structures are to be decided...
Eval:
  eval_name:
  eval_parameters:
Benchmark:
  benchmark_name:
  benchmark_type: