Dataset:
  dataset_name: 'CIFAR10LT'
  dataset_parameters:
    param1: '...'
    paramN: '...'
Dataloader:
  dataloader_name: '...'
  dataloader_parameters:
    param1: '...'
    paramN: '...'
Optim:
  optimizer_name: '...'
  optimizer_parameters:
    param1: '...'
    paramN: '...'
Model:
  model_name: '...'
  model_parameters:
    param1: '...'
    paramN: '...'
Loss:
  loss_name: '...'
  loss_parameters:
    param1: '...'
    paramN: '...'
Transform:
  transform_list:
    -
      transform_name:
        transform_params:
          param11: '...'
          param1N: '...',
    -
      transform_name:
        transform_params:
          paramN1: '...'
          paramNN: '...'
#Eval & Benchmark can be different from the other bases,
#Their structures are to be decided...
Eval:
  eval_name:
  eval_parameters:
Benchmark:
  benchmark_name:
  benchmark_type: