Dataset:
  #name: "IMB_CIFAR10"  # Mandatory field. Ignore in this defaults config.
  cifar10_imb_factor: 100
DataGeneration:
  batch_size: 128
  #datasets_path: "datasets/"  # Mandatory field. Ignore in this defaults config.
  train_shuffle: True
  draw_plots: False
  # Note that sampler is not passed through config file
Training:
  epoch_count: 100
  multi_gpu: False
  backup:
    #models_path: ""  # Mandatory field only if save_models or load_models is True.
    save_models: False
    load_models: False
  optimizer:
    name: "sgd"
    params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 2e-4
  tasks:
    # TODO [5]: Implement evaluation config. after separating the testing func.
    # TODO: Access tasks through unique names? IDs?
    -
      model: "resnet32"
      loss: "ce_softmax"
      #evaluation: ...  # TODO [5]
      task_options: None
  printing:
    print_training: True
    # TODO: Separate batch and epoch print frequencies
    print_frequency: 10
  draw_plots: False