Dataset:
  #datasets_path: "datasets/"  # Mandatory field. Ignore in this defaults config.
  #dataset_name: "CIFAR10"  # Mandatory field. Ignore in this defaults config.
  dataset_params:
    normalize_mu: (0.5, 0.5, 0.5)
    normalize_std: (0.5, 0.5, 0.5)
    jitter_brightness: 0.4
    jitter_contrast: 0.4
    jitter_saturation: 0.4
    jitter_hue: 0.25
DataGeneration:
  batch_size: 128
  pad: 4
  image_size: (32, 32)
  train_shuffle: True
  sampler: None
  plotting:
    draw_dataset_plots: False
    plot_size: (16, 12)
    plot_path: "output/dataset_plots/"
  train_transform:
    -
      transform_name: "pad"
      transform_params:
        fill: 0
        mode: "constant"
    -
      transform_name: "random_resized_crop"
      transform_params: None
    -
      transform_name: "random_horizontal_flip"
      transform_params: None
  test_transform:
    -
      transform_name: "center_crop"
      transform_params: None
Training:
  epoch_count: 100
  multi_gpu: False
  backup:
    #models_path: ""  # Mandatory field only if save_models or load_models is True.
    save_models: False
    load_models: False
  optimizer:
    name: "sgd"
    params:
      lr: 0.1
      lr_decay_epochs: [ ]
      lr_decay_rate: 0.1
      momentum: 0.9
      weight_decay: 2e-4
  tasks:
    -
      model: "resnet32"
      loss: "ce_softmax"
      task_options: None
  printing:
    print_training: True
    print_epoch_frequency: 1
    print_batch_frequency: 50
  plotting:
    draw_loss_plots: False
    plot_size: (16, 12)
    plot_path: "output/loss_plots/"
Evaluation:
  -
    method_name: "get_accuracy"
    method_params:
      calc_avg: True
      calc_perclass: False
      top: 1
      print_task_options: False
